name: 'Assign issue based on codeowners'
on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Assign to codeowners'
        uses: 'hmarr/auto-assign-issue@v3'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          owner-file: '.github/CODEOWNERS'

